### PR TITLE
Allows the configuration of a proxy for the HTTP client and the Colly HTTP client, Allows extracting precrawl links without matching the pattern

### PR DESCRIPTION
**Pull request by eyedeekay**
This PR adds a configuration option which allows a user to configure an `http://` or `socks://` proxy in the `lieu.toml`, and an additional option for extracting links from web sites that don't have a them in the form of `<li><a></a></li>`. My intent with this is to build a plugin to the I2P network which enhances the user's ability to search for sites by sharing the task of crawling sites and making it easy to run a small search engine. Simply setting the `http_proxy` environment variable does not appear to be sufficient due to DNS leakage, it must be done by replacing the default transport.

### CODE REVIEW

**Comment by cblgh** [comment]
@eyedeekay yooo this is a really cool use case for lieu, thanks for the patch! 🤩

i think i have a potentially nicer solution for the `NoWebring` option, but i'll add that in another PR and ping you for yr feedback :)

> My intent with this is to build a plugin to the I2P network which enhances the user's ability to search for sites by sharing the task of crawling sites and making it easy to run a small search engine

i'd love to learn a bit more about this! it is of particular interest as in one of the other projects i'm working on, [cabal](https://github.com/cabal-club/), we want add i2p compat :)

how are you thinking about sharing the task of crawling?

**Comment by eyedeekay** [comment]
I'm glad you like the idea. My plan right now is basically very simple. Java I2P(There are two implementations, one in Java and one in C++) has a plugin system which allows us to add services to an I2P configuration and tie their lifetime to the runtime of the I2P router. It also provides a way of encapsulating configuration and providing update, and most importantly it has this thing called the "Address Book" where you store locally-recognized human-readable petnames, which correspond to the cryptographic identity of a site. If you trim every line at the first `=`, i.e. `idk.i2p=mycrypgraphicidentifier` you end up with something that looks just like a precrawl file for `lieu` which is what gave me the idea. So an I2P user who installs the plugin will fetch their own `hosts.txt` file from their address book, trim it into a precrawl file, and use that to crawl the sites that they've stored. The *other* thing that I2P has is several unofficial services that aggregate addresses and provide listings for people to browse and optionally add to the address book. These usually present the information in the form of HTML pages with long lists of links in various formats, which is I was using `NoWebring` for. These also share the `hosts.txt` files that they generate, which people can "subscribe" to which, in turn, adds them to the local `hosts.txt` file, which periodically will be turned into a new precrawl file and be used to crawl sites. It's all sort of just waiting there for something to pull the information together and feed it into something that will organize it and make it searchable. Everybody will basically be able to be their own, custom search engine.

The only trouble is that will use an excess of bandwidth which I could save **if** I could also share, combine, and deduplicate the `crawled.txt` files as well. Not sure how to do that yet.

Had a look at cabal, I see it's in rust. Recently we've seen a little momentum on https://i2pgit.org/i2p-hackers/i2p-rs / https://github.com/i2p/i2p-rs which is a library for setting up I2P connections from rust applications using the "Simple Anonymous Messaging(SAMv3)" API, which will probably allow your people to provide your users with the best UX, since it will require the least amount of configuration on their parts.

**Comment by eyedeekay** [comment]
Removed the `NoWebring` option from this PR for now.

**Comment by cblgh** [comment]
@eyedeekay thanks! really appreciated the longer description of what you are trying to attempt, i think i understand what you're working towards :3 a personal i2p search engine sounds like a really cool addition to the wider i2p network! i'll try to get to the improved precrawl support with a PR of my own later this week

if i summarize what i gleaned from above:
* you are trying to export address books from inside i2p, trimming the output and then using the set of addresses as a kind of webring (i.e. starting the crawling from the set of addresses)
* you would want to combine the output from the address book export with that of the unofficial i2p address aggregators, resulting in a larger initial address set to work with. getting the input from the aggregators is something you wanted to accomplish with the `precrawl` command

re bandwidth: the crawler by default doesn't revisit urls it has already seen, but maybe that's not what you were getting at

**Comment by cblgh** [comment]
@eyedeekay i put together the custom selector behaviour i mentioned, check out https://github.com/cblgh/lieu/commit/b0ad7dce102d35123bb0092527b7ceea6df8ad86!

can you try setting a `webringSelector` field in your config with a css selector you think would grab all the links for your NoWebring case and let me know how that works?

i'm guessing that something like this would work for you
```toml
[general]
/* snip */
webringSelector = "a[href]"
/* snip */
```

**Comment by eyedeekay** [comment]
Perfect, that looks like it should work for everything I need it for. Thanks for doing it :)

**Comment by cblgh** [comment]
glad to hear that! :~

**Pull request merged**
